Repository ceramicnetwork/js-ceramic, pull requests merged in 2020-11, with the labels that each got.

#462 Fix Tile doctype test
  packages/ceramic-doctype-tile/src/__tests__/three-id.test.ts
  packages/ceramic-doctype-tile/src/__tests__/tile-doctype.test.ts
  packages/ceramic-doctype-tile/src/tile-doctype.ts
Labels: bug

#461 Apply standard flow for applyRecord
  packages/ceramic-core/src/ceramic.ts
  packages/ceramic-core/src/document.ts
Labels: bug, chore, enhancement

#463 bump cids version
  packages/ceramic-common/package.json
  packages/ceramic-core/package.json
  packages/ceramic-doctype-account-link/package.json
  packages/ceramic-doctype-tile/package.json
  packages/ceramic-http-client/package.json
  packages/docid/package.json
Labels: chore

#459 feat(tile): Fix metadata handling and test schema enforcement behavior
  packages/core/src/__tests__/ceramic-api.test.ts
  packages/doctype-tile/src/__tests__/__snapshots__/three-id.test.ts.snap
  packages/doctype-tile/src/__tests__/__snapshots__/tile-doctype.test.ts.snap
  packages/doctype-tile/src/tile-doctype-handler.ts
Labels: do not merge

#468 Serialize Doc ID
  packages/ceramic-cli/src/ceramic-daemon.ts
Labels: bug

#474 IDW dependency bump
  Dockerfile.daemon
  packages/ceramic-cli/package.json
  packages/ceramic-common/package.json
  packages/ceramic-core/package-lock.json
  packages/ceramic-core/package.json
  packages/ceramic-doctype-account-link/package-lock.json
  packages/ceramic-doctype-account-link/package.json
  packages/ceramic-doctype-tile/package-lock.json
  packages/ceramic-doctype-tile/package.json
  packages/ceramic-http-client/package-lock.json
Labels: additional work, bug

#488 Enable IPFS DHT functionality
  packages/ceramic-cli/src/ceramic-cli-utils.ts
Labels: additional work, bug

#504 Disable random walk for DHT
  packages/ceramic-cli/src/ceramic-cli-utils.ts
Labels: bug

#522 IPFS bump [HOTFIX]
  package-lock.json
  package.json
  packages/3id-did-resolver/package.json
  packages/3id-did-resolver/src/@types/ipfs.d.ts
  packages/ceramic-cli/package.json
  packages/ceramic-cli/src/@types/ipfs-http-client.d.ts
  packages/ceramic-cli/src/@types/ipfs.d.ts
  packages/ceramic-cli/src/__tests__/ceramic-daemon.test.ts
  packages/ceramic-cli/src/ceramic-cli-utils.ts
  packages/ceramic-cli/src/ceramic-daemon.ts
  packages/ceramic-cli/src/declarations.d.ts
  packages/ceramic-common/package-lock.json
  packages/ceramic-common/package.json
  packages/ceramic-common/src/@types/ipfs.d.ts
  packages/ceramic-common/src/ceramic-api.ts
  packages/ceramic-common/src/context.ts
  packages/ceramic-common/src/declarations.d.ts
  packages/ceramic-common/src/utils/doctype-utils.ts
  packages/ceramic-core/README.md
  packages/ceramic-core/package.json
  packages/ceramic-core/src/@types/3id-blockchain-utils.d.ts
  packages/ceramic-core/src/@types/ipfs-http-client.d.ts
  packages/ceramic-core/src/@types/ipfs.d.ts
  packages/ceramic-core/src/__tests__/ceramic-anchor.test.ts
  packages/ceramic-core/src/__tests__/ceramic-api.test.ts
  packages/ceramic-core/src/__tests__/ceramic.test.ts
  packages/ceramic-core/src/__tests__/ipfs-pinning.test.ts
  packages/ceramic-core/src/ceramic.ts
  packages/ceramic-core/src/declarations.d.ts
  packages/ceramic-core/src/dispatcher.ts
  packages/ceramic-core/src/pinning/ipfs-pinning.ts
  packages/ceramic-core/src/utils.ts
  packages/ceramic-doctype-account-link/package.json
  packages/ceramic-doctype-account-link/src/@types/ipfs.d.ts
  packages/ceramic-doctype-account-link/src/__tests__/account-link-doctype.test.ts
  packages/ceramic-doctype-account-link/src/account-link-doctype.ts
  packages/ceramic-doctype-tile/package.json
  packages/ceramic-doctype-tile/src/@types/ipfs.d.ts
  packages/ceramic-doctype-tile/src/tile-doctype.ts
  packages/ceramic-http-client/package.json
  packages/ceramic-http-client/src/@types/ipfs.d.ts
  packages/ceramic-http-client/src/ceramic-http-client.ts
  packages/key-did-resolver/package.json
  packages/key-did-resolver/src/index.ts
  tsconfig.json
Labels: bug

#523 Bump IPFS and level with master
  packages/3id-did-resolver/CHANGELOG.md
  packages/3id-did-resolver/package-lock.json
  packages/3id-did-resolver/package.json
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/cli/src/ceramic-cli-utils.ts
  packages/common/CHANGELOG.md
  packages/common/package-lock.json
  packages/common/package.json
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/core/package.json
  packages/core/src/@types/3id-blockchain-utils.d.ts
  packages/core/src/dispatcher.ts
  packages/core/src/utils.ts
  packages/doctype-caip10-link/CHANGELOG.md
  packages/doctype-caip10-link/package-lock.json
  packages/doctype-caip10-link/package.json
  packages/doctype-caip10-link/src/__tests__/caip10-link-doctype.test.ts
  packages/doctype-tile/CHANGELOG.md
  packages/doctype-tile/package-lock.json
  packages/doctype-tile/package.json
  packages/doctype-tile/src/tile-doctype.ts
  packages/http-client/CHANGELOG.md
  packages/http-client/package-lock.json
  packages/http-client/package.json
  packages/key-did-resolver/CHANGELOG.md
  packages/key-did-resolver/package-lock.json
  packages/key-did-resolver/package.json
  packages/key-did-resolver/src/index.ts
  packages/pinning-ipfs-backend/package.json
Labels: chore, dependencies

#533 Ceramic client config
  packages/cli/src/__tests__/ceramic-daemon.test.ts
  packages/http-client/src/ceramic-http-client.ts
  packages/http-client/src/document.ts
  packages/http-client/src/utils.ts
Labels: bug, chore, enhancement

#544 chore: bump to dids@1.0.0
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/common/package-lock.json
  packages/common/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/__tests__/document.test.ts
  packages/core/src/ceramic.ts
  packages/core/src/store/__tests__/state-store-integration.test.ts
  packages/doctype-tile/package-lock.json
  packages/doctype-tile/package.json
  packages/doctype-tile/src/__tests__/three-id.test.ts
  packages/doctype-tile/src/__tests__/tile-doctype.test.ts
  packages/http-client/package-lock.json
  packages/http-client/package.json
  packages/http-client/src/ceramic-http-client.ts
Labels: additional work

#546 IPFS API type import fixes
  packages/cli/package.json
  packages/cli/src/__tests__/ceramic-daemon.test.ts
  packages/cli/src/ceramic-cli-utils.ts
  packages/cli/src/ceramic-daemon.ts
  packages/cli/src/declarations.d.ts
  packages/common/package.json
  packages/common/src/context.ts
  packages/common/src/declarations.d.ts
  packages/common/src/index.ts
  packages/common/src/utils/doctype-utils.ts
  packages/core/package.json
  packages/core/src/__tests__/ceramic-anchor.test.ts
  packages/core/src/__tests__/ceramic-api.test.ts
  packages/core/src/__tests__/ceramic.test.ts
  packages/core/src/ceramic.ts
  packages/core/src/declarations.d.ts
  packages/core/src/dispatcher.ts
  packages/pinning-ipfs-backend/src/declarations.d.ts
  packages/pinning-ipfs-backend/src/index.ts
Labels: bug

#549 Fix resolver construction
  packages/http-client/src/ceramic-http-client.ts
Labels: bug

#565 IPFS API type import
  packages/common/src/index.ts
Labels: additional work, bug

#566 fix(doctype-tile): properly make new record when genesis is empty
  packages/doctype-tile/src/tile-doctype-handler.ts
Labels: additional work
