Repository ceramicnetwork/js-ceramic, pull requests merged in 2020-12, with the labels that each got.

#588 fix(doctype-tile): don't require auth when creating empty genesis records
  packages/doctype-tile/src/__tests__/tile-doctype.test.ts
  packages/doctype-tile/src/tile-doctype.ts
Labels: additional work

#587 fix(doctype-tile): bug in squashing logic was mitigated
  packages/doctype-tile/src/__tests__/__snapshots__/tile-doctype.test.ts.snap
  packages/doctype-tile/src/__tests__/tile-doctype.test.ts
  packages/doctype-tile/src/tile-doctype-handler.ts
  packages/doctype-tile/src/tile-doctype.ts
Labels: additional work

#601 Record types
  packages/cli/src/__tests__/ceramic-daemon.test.ts
  packages/cli/src/__tests__/ceramic-logger-plugins.test.ts
  packages/common/package.json
  packages/common/src/ceramic-api.ts
  packages/common/src/doctype.ts
  packages/common/src/utils/doctype-utils.ts
  packages/core/package.json
  packages/core/src/__tests__/ceramic.test.ts
  packages/core/src/ceramic.ts
  packages/core/src/document.ts
  packages/core/src/store/__tests__/level-state-store.test.ts
  packages/doctype-caip10-link/src/caip10-link-doctype-handler.ts
  packages/doctype-caip10-link/src/caip10-link-doctype.ts
  packages/doctype-tile/package.json
  packages/doctype-tile/src/__tests__/three-id.test.ts
  packages/doctype-tile/src/__tests__/tile-doctype.test.ts
  packages/doctype-tile/src/tile-doctype-handler.ts
  packages/doctype-tile/src/tile-doctype.ts
  packages/http-client/package.json
  packages/http-client/src/ceramic-http-client.ts
  packages/http-client/src/document.ts
Labels: API: Enhancement, enhancement

#605 Rename SignedRecordDTO to SignedRecordContainer
  packages/common/src/doctype.ts
  packages/common/src/utils/doctype-utils.ts
  packages/core/src/__tests__/ceramic-api.test.ts
  packages/core/src/__tests__/document.test.ts
  packages/core/src/ceramic.ts
  packages/core/src/dispatcher.ts
  packages/core/src/store/__tests__/state-store-integration.test.ts
Labels: API: Breaking, API: Enhancement

#608 fix(doctype-tile): unbreak tile makeGenesis metadata
  packages/doctype-tile/src/tile-doctype.ts
Labels: additional work

#607 Record size restriction
  packages/core/src/__tests__/ceramic-api.test.ts
  packages/core/src/__tests__/dispatcher.test.ts
  packages/core/src/dispatcher.ts
Labels: enhancement

#619 fix(doctype-caip10-link): solidify data structure
  packages/common/src/utils/doctype-utils.ts
  packages/doctype-caip10-link/src/__tests__/__snapshots__/caip10-link-doctype.test.ts.snap
  packages/doctype-caip10-link/src/__tests__/caip10-link-doctype.test.ts
  packages/doctype-caip10-link/src/caip10-link-doctype.ts
Labels: additional work

#626 Anchor service client fixes
  packages/core/src/anchor/ethereum/ethereum-anchor-service.ts
  packages/core/src/anchor/memory/in-memory-anchor-service.ts
Labels: chore

#638 CID version fix
  packages/3id-did-resolver/package.json
  packages/common/package.json
  packages/core/package.json
  packages/docid/package.json
  packages/doctype-caip10-link/package.json
  packages/doctype-tile/package.json
  packages/http-client/package.json
  packages/pinning-aggregation/package.json
  packages/pinning-ipfs-backend/package.json
  packages/pinning-powergate-backend/package.json
Labels: bug

#642 Use specific versions for multiformats dependencies
  packages/cli/package.json
  packages/core/package.json
  packages/docid/package.json
  packages/key-did-resolver/package.json
Labels: additional work, bug, chore

#641 SignedRecordContainer type import fix
  packages/doctype-tile/src/__tests__/three-id.test.ts
  packages/doctype-tile/src/__tests__/tile-doctype.test.ts
Labels: additional work, bug

#647 fix(docid): Add missing uint8array dep
  packages/docid/package.json
Labels: additional work, bug

#640 Remove squashing
  packages/common/src/doctype.ts
  packages/core/src/__tests__/ceramic-anchor.test.ts
  packages/core/src/__tests__/document.test.ts
  packages/core/src/anchor/memory/in-memory-anchor-service.ts
  packages/core/src/document.ts
  packages/doctype-tile/src/__tests__/__snapshots__/tile-doctype.test.ts.snap
  packages/doctype-tile/src/tile-doctype-handler.ts
  packages/doctype-tile/src/tile-doctype.ts
Labels: Protocol: Enhancement

#657 Change conflict resolution strategy
  packages/core/src/__tests__/document.test.ts
  packages/core/src/document.ts
Labels: Protocol: Breaking, Protocol: Enhancement

#667 IPFS dependency version
  packages/cli/package.json
  packages/common/package.json
  packages/core/package.json
  packages/pinning-ipfs-backend/package.json
Labels: additional work, bug

#673 fix(cli): rename healthcheck endpoint
  packages/cli/src/ceramic-daemon.ts
Labels: additional work

#720 Fix state comparison
  packages/common/src/utils/doctype-utils.ts
  packages/http-client/src/ceramic-http-client.ts
Labels: additional work, bug

#723 Remove refs property
  packages/common/src/doctype.ts
Labels: chore
