Repository ceramicnetwork/js-ceramic, pull requests merged in 2021-01, with the labels that each got.

#722 Docs LRU cache
  packages/common/package.json
  packages/common/src/doc-cache.ts
  packages/common/src/doctype.ts
  packages/common/src/index.ts
  packages/common/src/utils/doctype-utils.ts
  packages/core/package-lock.json
  packages/core/src/__tests__/ceramic-anchor.test.ts
  packages/core/src/__tests__/ceramic-api.test.ts
  packages/core/src/__tests__/ceramic.test.ts
  packages/core/src/ceramic.ts
  packages/core/src/document.ts
  packages/http-client/src/ceramic-http-client.ts
  packages/http-client/src/utils.ts
Labels: enhancement

#765 chore: Update default maintainer
  .dependabot/config.yml
  README.md
Labels: additional work

#791 fix(blockchain-utils-validation): add missing dep
  packages/blockchain-utils-validation/package.json
Labels: additional work

#800 chore: Update readme
  DEVELOPMENT.md
  README.md
  docs-src/http-api.md
  package.json
  typedoc.json
Labels: additional work

#803 fix(cli): controllers should not default to empty array on update
  packages/cli/src/ceramic-cli-utils.ts
Labels: bug

#844 fix(core): Properly ignore old FAILED anchor responses
  packages/core/src/document.ts
Labels: additional work
